"""Add user profile fields

Revision ID: 5945c05a5e59
Revises: b1f522df7032
Create Date: 2026-06-03 18:16:53.327588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5945c05a5e59'
down_revision: Union[str, None] = 'b1f522df7032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('college', sa.String(), nullable=True))
    op.add_column('users', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('target_role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'target_role')
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'degree')
    op.drop_column('users', 'college')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
